/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jsdroid_findimg_FindImg */

#ifndef _Included_com_jsdroid_findimg_FindImg
#define _Included_com_jsdroid_findimg_FindImg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jsdroid_findimg_FindImg
 * Method:    nativeFindImg
 * Signature: ([III[IIIIIIIIIIF[I)V
 */
JNIEXPORT void JNICALL Java_com_jsdroid_findimg_FindImg_nativeFindImg
  (JNIEnv *, jclass, jintArray, jint, jint, jintArray, jint, jint, jint, jint, jint, jint, jint, jint, jint, jfloat, jintArray);

#ifdef __cplusplus
}
#endif
#endif
